export const RECORD_ZIXUNSTATUS='RECORD_ZIXUNSTATUS';
export const RECORD_STRATEGYSTATUS='RECORD_STRATEGYSTATUS';
export const RECORD_SAISHISTATUS='RECORD_SAISHISTATUS';
export const RECORD_ZHIBOSTATUS='RECORD_ZHIBOSTATUS';
export const ALTER_NICKNAME='ALTER_NICKNAME';
export const ALTER_TEL='ALTER_TEL';
export const SHOWFOOT='SHOWFOOT';